---
- name: Phase 1 - Audit
  hosts: windows_runtime
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
        name: identity_access_control
        tasks_from: audit.yml
    - ansible.builtin.include_role:
        name: network_services_security
        tasks_from: audit.yml
    - ansible.builtin.include_role:
        name: auditing_monitoring
        tasks_from: audit.yml
    - ansible.builtin.include_role:
        name: system_hardening_antimalware
        tasks_from: audit.yml
