---
- name: Phase 2 - Remediation
  hosts: windows
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
        name: identity_access_control
        tasks_from: remediation.yml
    - ansible.builtin.include_role:
        name: network_services_security
        tasks_from: remediation.yml
    - ansible.builtin.include_role:
        name: auditing_monitoring
        tasks_from: remediation.yml
    - ansible.builtin.include_role:
        name: system_hardening_antimalware
        tasks_from: remediation.yml
