---
- name: Phase 4 - External Validation
  hosts: windows
  gather_facts: false
  vars:
    windows_active_admin_account_name: "{{ windows_identity_admin_target_name }}"
    ansible_user: ".\\{{ windows_identity_admin_target_name }}"
  tasks:
    - ansible.builtin.include_role:
        name: hardeningkitty_validation
        tasks_from: validate.yml
