ansible_connection: ssh
ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo
ansible_ssh_private_key_file: /vm-storage/Desktop/NT114-Q21-Speacialized-Project/jenkins-kvm-hub/key_pair/lab-key
wazuh_dashboard_admin_password: AdminWazuh9*
