#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
USAGE_TEMPLATE_PATH="${SCRIPT_DIR}/templates/generate-kvm-inventory.usage.txt"

LIBVIRT_URI="${LIBVIRT_URI:-qemu:///system}"
DC_DOMAIN_NAME="${DC_DOMAIN_NAME:-dc01}"
MEMBER_DOMAIN_NAME="${MEMBER_DOMAIN_NAME:-member01}"
OUTPUT_PATH="${OUTPUT_PATH:-${PROJECT_ROOT}/ansible/inventories/kvm/windows_server.ini}"

ANSIBLE_WIN_USER="${ANSIBLE_WIN_USER:-Administrator}"
ANSIBLE_WIN_PASSWORD="${ANSIBLE_WIN_PASSWORD:-}"
ANSIBLE_WINRM_PORT="${ANSIBLE_WINRM_PORT:-5985}"
ANSIBLE_WINRM_TRANSPORT="${ANSIBLE_WINRM_TRANSPORT:-ntlm}"
ANSIBLE_WINRM_CERT_VALIDATION="${ANSIBLE_WINRM_CERT_VALIDATION:-ignore}"

usage() {
  if [[ ! -f "${USAGE_TEMPLATE_PATH}" ]]; then
    echo "Usage template not found: ${USAGE_TEMPLATE_PATH}" >&2
    exit 1
  fi

  cat "${USAGE_TEMPLATE_PATH}"
}

if [[ "${1:-}" =~ ^(-h|--help|help)$ ]]; then
  usage
  exit 0
fi

if ! command -v virsh >/dev/null 2>&1; then
  echo "virsh is required but not found in PATH."
  exit 1
fi

get_ipv4_from_lease() {
  local domain="$1"
  local ip=""
  ip="$(
    virsh -c "${LIBVIRT_URI}" domifaddr "${domain}" --source lease 2>/dev/null \
      | awk '/ipv4/ {print $4}' \
      | cut -d/ -f1 \
      | head -n1 || true
  )"
  printf "%s" "${ip}"
}

dc_ip="$(get_ipv4_from_lease "${DC_DOMAIN_NAME}")"
member_ip="$(get_ipv4_from_lease "${MEMBER_DOMAIN_NAME}")"

if [[ -z "${dc_ip}" ]]; then
  echo "Could not resolve DHCP IPv4 lease for domain '${DC_DOMAIN_NAME}'."
  echo "Ensure the VM is running and attached to a DHCP-enabled libvirt network."
  exit 1
fi

if [[ -z "${member_ip}" ]]; then
  echo "Could not resolve DHCP IPv4 lease for domain '${MEMBER_DOMAIN_NAME}'."
  echo "Ensure the VM is running and attached to a DHCP-enabled libvirt network."
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_PATH}")"

if [[ -z "${ANSIBLE_WIN_PASSWORD}" ]]; then
  ANSIBLE_WIN_PASSWORD="ChangeMe123!Strong"
  echo "ANSIBLE_WIN_PASSWORD is empty; writing placeholder password to inventory."
fi

cat > "${OUTPUT_PATH}" <<EOF
# Generated by kvm/scripts/generate-kvm-inventory.sh

[windows]
${DC_DOMAIN_NAME} ansible_host=${dc_ip}
${MEMBER_DOMAIN_NAME} ansible_host=${member_ip}

[domain_controller]
${DC_DOMAIN_NAME}

[member_server]
${MEMBER_DOMAIN_NAME}

[windows:vars]
ansible_user=${ANSIBLE_WIN_USER}
ansible_password=${ANSIBLE_WIN_PASSWORD}
ansible_connection=winrm
ansible_port=${ANSIBLE_WINRM_PORT}
ansible_winrm_transport=${ANSIBLE_WINRM_TRANSPORT}
ansible_winrm_server_cert_validation=${ANSIBLE_WINRM_CERT_VALIDATION}
EOF

echo "Inventory generated at: ${OUTPUT_PATH}"
echo "  ${DC_DOMAIN_NAME}     -> ${dc_ip}"
echo "  ${MEMBER_DOMAIN_NAME} -> ${member_ip}"
