---
- name: HardeningKitty precheck
  ansible.builtin.include_tasks: precheck.yml

- name: HardeningKitty execute
  ansible.builtin.include_tasks: execute.yml
  when: hardeningkitty_validation_ready | bool

- name: HardeningKitty collect artifacts
  ansible.builtin.include_tasks: collect.yml
  when: hardeningkitty_validation_ready | bool

- name: HardeningKitty summarize results
  ansible.builtin.include_tasks: summarize.yml
  when: hardeningkitty_validation_ready | bool

- name: HardeningKitty aggregate summaries
  ansible.builtin.include_tasks: aggregate.yml
  when: hardeningkitty_enabled | bool
